<?php
// module/Article/view/article/article/add.phtml

$title = 'Add a new article';
$this->headTitle($title);
?>
<h1><?php echo $this->wdevMarkdown($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('article/add'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('content'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->CloseTag();

// echo $this->formCollection($form);
