<?php
// module/Article/view/article/article/add.phtml
if (!empty($_REQUEST['content'])) {
	echo '<pre>';
	print_r($_REQUEST);
	echo '</pre>';
}
/*-----------------Aloha Editor---------------------------*/
?>
<!-- load the jQuery and require.js libraries -->
              <script type="text/javascript" src="http://cdn.aloha-editor.org/latest/lib/vendor/jquery-1.7.2.js"></script>
              <script type="text/javascript" src="http://cdn.aloha-editor.org/latest/lib/require.js"></script>
 
              <!-- load the Aloha Editor core and some plugins -->
              <script src="http://cdn.aloha-editor.org/latest/lib/aloha.js"
                                   data-aloha-plugins="common/ui,
                                                        common/format,
                                                        common/list,
                                                        common/link,
                                                        common/highlighteditables">
              </script>
               
              <!-- load the Aloha Editor CSS styles -->
              <link href="http://cdn.aloha-editor.org/latest/css/aloha.css" rel="stylesheet" type="text/css" />
<?php
/*-----------------Aloha Editor---------------------------*/



$title = 'Add a new article';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('article', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('content'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->CloseTag();

// echo $this->formCollection($form);
?>

<script type="text/javascript">
	Aloha.ready( function(){
		var $ = Aloha.jQuery;
		$('#content').aloha();

		$('#submitForm').click(function(){
			$("form:first").submit(); 
		});
	});
</script>
<?php
