<?php
// module/Article/view/article/article/delete.phtml

$title = 'Delete article';
$this->headTitle($title);
?>
<h1><?php echo $this->WdevMarkdown($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->WdevMarkdown($article->title); ?>'?
</p>



<form action="<?php echo $article->id; ?>" method="post" data-ajax="false">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->escapeHtml($article->id); ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>