<?php
// module/Article/view/article/article/delete.phtml

$title = 'Delete article';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($article->title); ?>'?
</p>

<?php 
$url = $this->url('article', array(
    'action' => 'delete',
    'title' => $this->title,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="title" value="<?php echo $this->escapeHtml($article->title); ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>