<?php
// module/Article/view/article/article/index.phtml:

$title = 'Ramblings, thoughts and other ideas';
$this->headTitle($title);
?>
 <?php $this->WdevMarkdown(); ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php IF($this->zfcUserIdentity()): ?>
<p>
    <a href="<?php echo $this->url('article/add');?>">Add new Article</a>
</p>
<?php ENDIF ?>
<article>
      
   <?php foreach ($articles as $article) : ?>
    <section>
        <article>
        <a href="article/view/<?php echo $article->id;?>"><?php echo $this->WdevMarkdown($article->title);?></a>
        
            <?php $this->WdevMarkdown($article->content); ?>
        
        
            <a href="article/view/<?php echo $article->id;?>">View</a>
            <?php IF($this->zfcUserIdentity()): ?>
            <a href="article/edit/<?php echo $article->id;?>">Edit</a>
            <a href="article/delete/<?php echo $article->id;?>">Delete</a>
            <?php ENDIF ?>
        </article>
        <br />
    </section>
   <?php endforeach; ?>
      
</article>