<?php
// module/Article/view/article/article/index.phtml:

$title = 'My Articles';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('article/add');?>">Add new Article</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Content</th>
        <th>&nbsp;</th>
    </tr>
    
   <?php foreach ($articles as $article) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($article->title);?></td>
        <td><?php echo $article->content; ?></td>
        <td><?php echo $article->id; ?></td>
        
        <td>
            <a href="article/view/<?php echo $article->id;?>">View</a>
            <a href="article/edit/<?php echo $article->id;?>">Edit</a>
            <a href="article/delete/<?php echo $article->id;?>">Delete</a>
        </td>
    </tr>
   <?php endforeach; ?>
